name: macOS ARM Test

on:
  workflow_dispatch:

jobs:
  test-arm:
    runs-on: macos-26

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      - name: Systeminformationen anzeigen
        run: |
          uname -a
          arch
          sw_vers
